# https://starship.rs/config/

# Don't print a new line at the start of the prompt
# add_newline = false

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[character]
# Just a boring $ for me!
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
